package GUI;

import Game.Player;
import ThreeCardPoker.ThreeCardPoker;
import User.AllUsers;
import User.User;

import java.text.NumberFormat;
import java.util.Stack.*;

import Game.Player;
import Game.Dealer;
import jdk.jfr.StackTrace;

import javax.swing.JFrame;
import java.util.Stack;

/**
 *
 * @author James
 */
public class GameMenu extends javax.swing.JFrame {

    private User user = AllUsers.readFile().get(AllUsers.getCurrentUser());

    /**
     * Creates new form LoginForm
     */
    public GameMenu() {
        initComponents();
        this.setLocationRelativeTo(null);

        BalenceText.setText("Chip Balance: " + FormatNumber(user.getChipBalance()));
        UserText.setText("User: " + user.getLogin().getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        Hedder = new javax.swing.JPanel();
        LoginText = new javax.swing.JLabel();
        Minimise = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        UserText = new javax.swing.JLabel();
        BalenceText = new javax.swing.JLabel();
        TCP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RL = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Slots = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BJ = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Hedder.setBackground(new java.awt.Color(145, 180, 150));

        LoginText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LoginText.setForeground(new java.awt.Color(255, 255, 255));
        LoginText.setText("Casino - Choose Game");

        Minimise.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Minimise.setForeground(new java.awt.Color(255, 255, 255));
        Minimise.setText("-");
        Minimise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiseMouseClicked(evt);
            }
        });

        Close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Close.setForeground(new java.awt.Color(255, 255, 255));
        Close.setText("X");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        LogOut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogOut.setForeground(new java.awt.Color(102, 0, 0));
        LogOut.setText("LOG OUT");
        LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HedderLayout = new javax.swing.GroupLayout(Hedder);
        Hedder.setLayout(HedderLayout);
        HedderLayout.setHorizontalGroup(
                HedderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HedderLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(LoginText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LogOut)
                                .addGap(18, 18, 18)
                                .addComponent(Minimise)
                                .addGap(18, 18, 18)
                                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        HedderLayout.setVerticalGroup(
                HedderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HedderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Minimise, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(LoginText)
                                .addComponent(Close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LogOut))
        );

        Body.setBackground(new java.awt.Color(46, 49, 49));

        UserText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserText.setForeground(new java.awt.Color(218, 223, 225));
        UserText.setText("USER: ");

        BalenceText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BalenceText.setForeground(new java.awt.Color(218, 223, 225));
        BalenceText.setText("Chip Balance: ");

        TCP.setBackground(new java.awt.Color(0, 102, 51));
        TCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TCPMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Three Card Poker");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout TCPLayout = new javax.swing.GroupLayout(TCP);
        TCP.setLayout(TCPLayout);
        TCPLayout.setHorizontalGroup(
                TCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        TCPLayout.setVerticalGroup(
                TCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        RL.setBackground(new java.awt.Color(0, 102, 51));
        RL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RLMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Roulette");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout RLLayout = new javax.swing.GroupLayout(RL);
        RL.setLayout(RLLayout);
        RLLayout.setHorizontalGroup(
                RLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        RLLayout.setVerticalGroup(
                RLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        Slots.setBackground(new java.awt.Color(0, 102, 51));
        Slots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SlotsMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Slots");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout SlotsLayout = new javax.swing.GroupLayout(Slots);
        Slots.setLayout(SlotsLayout);
        SlotsLayout.setHorizontalGroup(
                SlotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        SlotsLayout.setVerticalGroup(
                SlotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        BJ.setBackground(new java.awt.Color(0, 102, 51));
        BJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BJMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Black Jack");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BJLayout = new javax.swing.GroupLayout(BJ);
        BJ.setLayout(BJLayout);
        BJLayout.setHorizontalGroup(
                BJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        BJLayout.setVerticalGroup(
                BJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
                BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BodyLayout.createSequentialGroup()
                                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BodyLayout.createSequentialGroup()
                                                        .addGap(31, 31, 31)
                                                        .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(BodyLayout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(BalenceText, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(BodyLayout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(BodyLayout.createSequentialGroup()
                                                                .addComponent(Slots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(93, 93, 93)
                                                                .addComponent(RL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(BodyLayout.createSequentialGroup()
                                                                .addComponent(TCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(93, 93, 93)
                                                                .addComponent(BJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(58, 58, 58))
        );
        BodyLayout.setVerticalGroup(
                BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BodyLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BalenceText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(BodyLayout.createSequentialGroup()
                                                .addComponent(TCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Slots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(RL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(BJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Hedder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(Hedder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void MinimiseMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("[Class: GameMenu] MinimiseMouseClicked() Called");
        this.setState(JFrame.ICONIFIED);

    }

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("[Class: GameMenu] CloseMouseClicked() Called");
        System.exit(0);

    }

    private void BJMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("[Class: GameMenu] BJMouseClicked() Called");
        // TODO add your handling code here:
    }

    private void SlotsMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("[Class: GameMenu] SlotsMouseClicked() Called");
        // TODO add your handling code here:
    }

    private void RLMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("[Class: GameMenu] RLMouseClicked() Called");
        // TODO add your handling code here:
    }

    private void TCPMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("[Class: GameMenu] TCPMouseClicked() Called");
        this.setState(JFrame.ICONIFIED);
        ThreeCardPoker tp = new ThreeCardPoker();
        tp.setVisible(true);
        this.dispose();
    }

    public static void printStackTrace() {
        StackTraceElement[] elements = Thread.currentThread().getStackTrace();
        System.out.println("Printing stack trace, current length: " + elements.length);
        for (int i = 0; i < elements.length; i++) {
            StackTraceElement s = elements[i];
            System.out.println("\t at "
                    + s.getClassName() + "."
                    + s.getMethodName()
                    + "(" + s.getFileName() + ":" + s.getLineNumber() + ")");
        }
        System.out.println("\n");
    }

    private String FormatNumber(int Num){
        String s = NumberFormat.getIntegerInstance().format(Num);
        return s;
    }


    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("[Class: GameMenu] LogOutMouseClicked() Called");
        AllUsers.UpdateFile(user);
        AllUsers.setCurrentUser(-1);
        this.setState(JFrame.ICONIFIED);
        LoginGUI Ln = new LoginGUI();
        Ln.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */






    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel BJ;
    private javax.swing.JLabel BalenceText;
    private javax.swing.JPanel Body;
    private javax.swing.JLabel Close;
    private javax.swing.JPanel Hedder;
    private javax.swing.JLabel LogOut;
    private javax.swing.JLabel LoginText;
    private javax.swing.JLabel Minimise;
    private javax.swing.JPanel RL;
    private javax.swing.JPanel Slots;
    private javax.swing.JPanel Slots1;
    private javax.swing.JPanel TCP;
    private javax.swing.JPanel TCP2;
    private javax.swing.JPanel TCP3;
    private javax.swing.JPanel TCP4;
    private javax.swing.JPanel TCP5;
    private javax.swing.JLabel UserText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration
}
